// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PollTasksController from "./poll_tasks_controller"
application.register("poll-tasks", PollTasksController)

import TaskActionController from "./task_action_controller"
application.register("task-action", TaskActionController)

import ToastsController from "./toasts_controller"
application.register("toasts", ToastsController)
